# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QJsonTranslatorExample
DESTDIR = ./out/bin/x32
QT += core gui
CONFIG += release
DEFINES += QT_LARGEFILE_SUPPORT
INCLUDEPATH += ./QJsonTranslatorExample/GeneratedFiles \
    ./QJsonTranslatorExample/GeneratedFiles/Release \
    ./QJsonTranslatorExample
DEPENDPATH += .
MOC_DIR += ./QJsonTranslatorExample/GeneratedFiles/release
OBJECTS_DIR += release
UI_DIR += ./QJsonTranslatorExample/GeneratedFiles
RCC_DIR += ./QJsonTranslatorExample/GeneratedFiles
HEADERS += ./QJsonTranslatorExample/json.h \
    ./QJsonTranslatorExample/qjsontranslatorexample.h \
    ./QJsonTranslatorExample/qjsontranslator.h
SOURCES += ./QJsonTranslatorExample/json.cpp \
    ./QJsonTranslatorExample/main.cpp \
    ./QJsonTranslatorExample/qjsontranslator.cpp \
    ./QJsonTranslatorExample/qjsontranslatorexample.cpp
FORMS += ./QJsonTranslatorExample/qjsontranslatorexample.ui
RESOURCES += ./QJsonTranslatorExample/qjsontranslatorexample.qrc
