# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QTestExampleWidget
DESTDIR = ./out/bin/x32
QT += core gui
CONFIG += release
DEFINES += QT_LARGEFILE_SUPPORT
INCLUDEPATH += ./QTestExampleWidget/GeneratedFiles \
    ./QTestExampleWidget/GeneratedFiles/Release \
    ./QTestExampleWidget
DEPENDPATH += .
MOC_DIR += ./QTestExampleWidget/GeneratedFiles/release
OBJECTS_DIR += release
UI_DIR += ./QTestExampleWidget/GeneratedFiles
RCC_DIR += ./QTestExampleWidget/GeneratedFiles
HEADERS += ./QTestExampleWidget/qvolumemeter.h \
    ./QTestExampleWidget/qtestexamplewidget.h
SOURCES += ./QTestExampleWidget/main.cpp \
    ./QTestExampleWidget/qtestexamplewidget.cpp \
    ./QTestExampleWidget/qvolumemeter.cpp
FORMS += ./QTestExampleWidget/qtestexamplewidget.ui
RESOURCES += ./QTestExampleWidget/qtestexamplewidget.qrc
